apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-api
  labels:
    app: poc-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-api
  template:
    metadata:
      labels:
        app: poc-api
    spec:
      containers:
        - name: poc-api
          image: 339712793019.dkr.ecr.ap-south-1.amazonaws.com/dev-api-repo-liberal-polecat:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
